### PR TITLE
Janus 1.1.0

### PR DESCRIPTION
**Pull request by yzainee-zz**

### CODE REVIEW

**Review by miteshvp — CHANGES_REQUESTED** [review]
This is definitely spoiling commit history for this repo. Please squash. One more question, what is additional to #42

**Comment by msrb** [comment]
Please do not create branches in this repository :)

Here's how you do it:

One-time thing, prepare your environment:

```
$ git clone git@github.com:fabric8-analytics/gremlin-docker.git
$ cd gremlin-docker/
$ git remote add fork git@github.com:yzainee/gremlin-docker.git
```

Then, every time you want to open a new PR:

```
$ git checkout master
$ git pull
$ git checkout -b new-branch-name
``` 

Do your changes, and commit.
Then push your changes to your fork:

```
$ git push -u fork new-branch-name
```

Open a PR.

**Comment by msrb** [comment]
And here's some recommended reading for rainy days: https://git-scm.com/book/en/v2 :)

**Comment by msrb** [comment]
> One more question, what is additional to #42

+1, I am also a bit confused here.

**Pull request closed without merging**
