### PR TITLE
Janus 1.1.0

### PR DESCRIPTION
**Pull request by yzainee-zz**

### CODE REVIEW

**Comment by miteshvp** [comment]
@yzainee - can we disable console reporting as well in `gremlin-server.yaml`
```
metrics: {
  consoleReporter: {enabled: false},
  csvReporter: {enabled: false},
  jmxReporter: {enabled: false},
  slf4jReporter: {enabled: false},
  gangliaReporter: {enabled: false},
  graphiteReporter: {enabled: false}
}
```

**Review by msrb — APPROVED** [review]
Great job @yzainee :wink: Feel free to hit the merge button :+1:

**Comment by miteshvp** [comment]
@yzainee - LGTM. Is it ok to squash your commits?

**Review by miteshvp — APPROVED** [review]

**Comment by miteshvp** [comment]
Based on the discussion, it is better to squash those un-necessary commits into one, since most of the commits were trial and error but then let it be.

**Pull request merged**
